version: "2"
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
    worker:
        image: registry.cn-hangzhou.aliyuncs.com/lisong/cognitive:$VERSION
        networks:
            - frontend
        depends_on:
            - redis
        ports:
            - "8080:8080"
networks:
    frontend:
